---
deployment:
  tasks:
    - /bin/mkdir -p /home/ymoepkke/public_html/media
    - /bin/cp -R media/. /home/ymoepkke/public_html/media/
    - /bin/cp index.html /home/ymoepkke/public_html/index.html
